version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      chai:
        patterns:
          - chai
          - chai-as-promised
      eslint:
        patterns:
          - '@egy186/eslint-config'
          - '@vitest/eslint-plugin'
          - eslint
      vitest:
        patterns:
          - '@vitest/*'
          - vitest
    cooldown:
      default-days: 3
      exclude:
        - '@egy186/*'
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
