version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "@rollup/plugin-babel"
          - "babel-plugin-*"
      chai:
        patterns:
          - "chai"
          - "chai-as-promised"
      eslint:
        patterns:
          - "@egy186/eslint-config"
          - "@stylistic/eslint-plugin"
          - "eslint"
          - "eslint-plugin-*"
          - "globals"
      playwright:
        patterns:
          - "@playwright/test"
          - "playwright"
      rollup:
        patterns:
          - "@rollup/plugin-*"
          - "rollup"
    versioning-strategy: increase
