version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      chai:
        patterns:
          - chai
          - chai-as-promised
      eslint:
        patterns:
          - '@egy186/eslint-config'
          - eslint
      playwright:
        patterns:
          - '@playwright/test'
          - playwright
    cooldown:
      default-days: 3
      exclude:
        - '@egy186/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
