version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      babel:
        patterns:
          - '@babel/*'
      chai:
        patterns:
          - chai
          - chai-as-promised
      eslint:
        patterns:
          - '@egy186/eslint-config'
          - eslint
      playwright:
        patterns:
          - '@playwright/test'
          - playwright
      rollup:
        patterns:
          - '@rollup/plugin-'
          - rollup
    cooldown:
      default-days: 3
      exclude:
        - '@egy186/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
