name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    if: github.repository == 'egy186/icojs'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish
      run: npm publish
